name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js (optional, if you have JS dependencies)
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies (if needed)
        run: |
          npm install

      - name: Run tests (optional)
        run: |
          npm test

      - name: Deploy to server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
        run: |
          ssh -i $SSH_PRIVATE_KEY $SERVER_USER@$SERVER_IP "cd /path/to/your/project && git pull origin main"
